"""empty message

Revision ID: 1fff4aaa69da
Revises: 
Create Date: 2021-01-30 13:30:26.728394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fff4aaa69da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=400), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url_en', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('url_en')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('parent_uuid', sa.String(length=500), nullable=True),
    sa.Column('parent_name', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('agent', sa.String(length=500), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('comment_type', sa.String(length=300), nullable=False),
    sa.Column('guest_name', sa.String(length=200), nullable=False),
    sa.Column('guest_email', sa.String(length=300), nullable=False),
    sa.Column('hash_email', sa.String(length=300), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('web_site', sa.String(length=300), nullable=True),
    sa.Column('uuid', sa.String(length=300), nullable=True),
    sa.Column('show_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commet_parent_uuid'), 'commet', ['parent_uuid'], unique=False)
    op.create_index(op.f('ix_commet_post_id'), 'commet', ['post_id'], unique=False)
    op.create_index(op.f('ix_commet_user_id'), 'commet', ['user_id'], unique=False)
    op.create_table('py_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('link', sa.String(length=1000), nullable=False),
    sa.Column('avatar', sa.String(length=1000), nullable=False),
    sa.Column('brief', sa.String(length=1000), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=400), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=True),
    sa.Column('github', sa.String(length=400), nullable=True),
    sa.Column('bilibili', sa.String(length=400), nullable=True),
    sa.Column('showName', sa.String(length=60), nullable=True),
    sa.Column('mail_hash', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bilibili'),
    sa.UniqueConstraint('github'),
    sa.UniqueConstraint('mail_hash'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('showName')
    )
    op.create_index(op.f('ix_user_mail'), 'user', ['mail'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('article_category',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'category_id')
    )
    op.create_table('article_tag',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_tag')
    op.drop_table('article_category')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_mail'), table_name='user')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('py_link')
    op.drop_index(op.f('ix_commet_user_id'), table_name='commet')
    op.drop_index(op.f('ix_commet_post_id'), table_name='commet')
    op.drop_index(op.f('ix_commet_parent_uuid'), table_name='commet')
    op.drop_table('commet')
    op.drop_table('category')
    op.drop_table('article')
    # ### end Alembic commands ###
