"""empty message

Revision ID: a7a74ac34853
Revises: 
Create Date: 2020-06-13 23:02:29.081256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a74ac34853'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=400), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.String(length=100), nullable=False),
    sa.Column('url_en', sa.String(length=200), nullable=True),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('template', sa.Text(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('url_en')
    )
    op.create_table('parent_commet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('guest_name', sa.String(length=200), nullable=False),
    sa.Column('guest_email', sa.String(length=300), nullable=False),
    sa.Column('hash_email', sa.String(length=300), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('web_site', sa.String(length=300), nullable=True),
    sa.Column('uuid', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_commet_post_id'), 'parent_commet', ['post_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=400), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=True),
    sa.Column('github', sa.String(length=400), nullable=True),
    sa.Column('bilibili', sa.String(length=400), nullable=True),
    sa.Column('showName', sa.String(length=60), nullable=True),
    sa.Column('mail_hash', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bilibili'),
    sa.UniqueConstraint('github'),
    sa.UniqueConstraint('mail_hash'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('showName')
    )
    op.create_index(op.f('ix_user_mail'), 'user', ['mail'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('children_commet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('guest_name', sa.Text(), nullable=False),
    sa.Column('guest_email', sa.Text(), nullable=False),
    sa.Column('hash_email', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('web_site', sa.String(length=300), nullable=True),
    sa.Column('uuid', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parent_commet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('children_commet')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_mail'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_parent_commet_post_id'), table_name='parent_commet')
    op.drop_table('parent_commet')
    op.drop_table('content')
    # ### end Alembic commands ###
